remote_theme: pmarsceill/just-the-docs
title: LASER Help Docs
description: Collection of guides on how to conduct research within LASER 
# logo: https://lida.leeds.ac.uk/wp-content/uploads/2016/04/LIDA-logo.png
