### Basic details
title: IG Training
author: LIDA Data Analytics Team (DAT)
email: dat@leeds.ac.uk
description: Collection of guides on how to conduct research within LIDA 

### Site build settings
#theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
 
### License config
license: GNU GPLv3
license_url: https://www.gnu.org/licenses/gpl-3.0.html

gems:
  - jekyll-paginate

paginate: 5 # Number of posts per page
paginate_path: "/page:num/"


